Album.create!([
  {id: 1, album_name: "Ohh What A Night", artist_id: 1},
  {id: 2, album_name: "Still Bill", artist_id: 2},
  {id: 3, album_name: "Love", artist_id: 3},
  {id: 4, album_name: "Birth Of The Cool", artist_id: 4},
  {id: 5, album_name: "In Hi-Fi", artist_id: 5},
  {id: 6, album_name: "Led Zeppelin IV", artist_id: 6},
  {id: 7, album_name: "Heart", artist_id: 7},
  {id: 8, album_name: "Mary", artist_id: 8},
  {id: 9, album_name: "Fair Corporation", artist_id: 9},
  {id: 10, album_name: "Frank Zappa", artist_id: 10},
  {id: 11, album_name: "The Beatles Greatest Hits", artist_id: 11},
  {id: 12, album_name: "All Ray", artist_id: 12},
  {id: 13, album_name: "Songs of The Beatles", artist_id: 13},
  {id: 14, album_name: "Classic Compositions", artist_id: 14},
  {id: 15, album_name: "All Alice", artist_id: 15},
  {id: 16, album_name: "Minnie", artist_id: 16},
  {id: 17, album_name: "Best of The Stylistics", artist_id: 17},
  {id: 18, album_name: "B-Day", artist_id: 18}
])
Artist.create!([
  {id: 1, artist_name: "The Dells"},
  {id: 2, artist_name: "Bill Withers"},
  {id: 3, artist_name: "Billy Paul"},
  {id: 4, artist_name: "Miles Davis"},
  {id: 5, artist_name: "Sarah Vaughn"},
  {id: 6, artist_name: "Led Zeppelin"},
  {id: 7, artist_name: "Heart"},
  {id: 8, artist_name: "Mary J. Blige"},
  {id: 9, artist_name: "Fair Corporation"},
  {id: 10, artist_name: "Frank Zappa"},
  {id: 11, artist_name: "The Beatles"},
  {id: 12, artist_name: "Ray Charles"},
  {id: 13, artist_name: "Chick Corea"},
  {id: 14, artist_name: "Aretha Franklin"},
  {id: 15, artist_name: "Alice Cooper"},
  {id: 16, artist_name: "Minnie Riperton"},
  {id: 17, artist_name: "The Stylistics"},
  {id: 18, artist_name: "Beyonce"}
])
Song.create!([
  {id: 1, song_name: "Ohh What A Night", artist_id: 1, album_id: 1},
  {id: 2, song_name: "Lean On Me", artist_id: 2, album_id: 2},
  {id: 3, song_name: "Me and Mrs. Jones", artist_id: 3, album_id: 3},
  {id: 4, song_name: "Move", artist_id: 4, album_id: 4},
  {id: 5, song_name: "It Might As Well Be Spring", artist_id: 5, album_id: 5},
  {id: 6, song_name: "Stairway To Heaven", artist_id: 6, album_id: 6},
  {id: 7, song_name: "Stairway To Heaven", artist_id: 7, album_id: 7},
  {id: 8, song_name: "Stairway To Heaven", artist_id: 8, album_id: 8},
  {id: 9, song_name: "Stairway To Heaven", artist_id: 9, album_id: 9},
  {id: 10, song_name: "Stairway To Heaven", artist_id: 10, album_id: 10},
  {id: 11, song_name: "Eleanor Rigby", artist_id: 11, album_id: 11},
  {id: 12, song_name: "Eleanor Rigby", artist_id: 12, album_id: 12},
  {id: 13, song_name: "Eleanor Rigby", artist_id: 13, album_id: 13},
  {id: 14, song_name: "Eleanor Rigby", artist_id: 14, album_id: 14},
  {id: 15, song_name: "Eleanor Rigby", artist_id: 15, album_id: 15},
  {id: 16, song_name: "Loving You", artist_id: 16, album_id: 16},
  {id: 17, song_name: "You Make Me Feel Brand New", artist_id: 17, album_id: 17},
  {id: 18, song_name: "Get Bodied", artist_id: 18, album_id: 18}
])
